# Generated by Django 3.0.6 on 2020-05-28 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 16, 26, 36, 701525, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='items',
            name='video',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cats',
            name='location',
            field=models.CharField(blank=True, choices=[('nav', 'navigation panel'), ('main', 'mainpage'), ('footer', 'Footer')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.TextField(),
        ),
    ]
