# Generated by Django 3.0.6 on 2020-06-01 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 1, 10, 39, 24, 470031, tzinfo=utc)),
        ),
    ]
