# Generated by Django 3.0.6 on 2020-06-04 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200602_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='location',
            field=models.CharField(blank=True, choices=[('nav', 'navigation panel'), ('main', 'mainpage'), ('footer', 'Footer'), ('side_menu', 'side_menu')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 4, 14, 25, 58, 127991, tzinfo=utc)),
        ),
    ]
